---
title: "Producing results"
output: word_document
date: "2025-02-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(treemap)
```

Add a sentence here

## Libraries
```{r}
library(tidyverse)
library(cowplot)
```

## Read data
```{r}
Whale<-read.csv("Data/Humpback.csv") %>% filter(length.m.>0)
Whale$sex<-factor(Whale$sex, levels = c("Male", "Female", "Hermaphrodite", "Unknown"))

```


### Plot % Male vs Year
```{r}
male_year<-Whale %>%
  group_by(Year) %>%
  summarise(Prop_male=sum(sex=="Male")/n(),n=n())%>%
  filter(Year>=1949 & Year<=1962)

ggplot(male_year, aes(x=Year,y=Prop_male),)+
  geom_line()+
  geom_smooth(linewidth = 0.5,colour = "red", se = FALSE) +
  geom_line(aes(y=0.5), linetype=2)+
  coord_cartesian(ylim = c(0.25,0.90))+
  labs(x="Year",y="% Male")
```

```{r}
whale1<-Whale %>%
  filter(sex =="Male" | sex =="Female") %>%
  droplevels()

prop.table(table(whale1$sex))


```

## Permutation test 1000 perms
```{r}

mostra1<-sample(whale1$sex,200, replace=FALSE)
table(mostra1)
#mostra1
#  Male Female 
#   121     79 
NumOfHeads<-c()
for (i in 1:10000){
  mostrai<-sample(c(0,1),200, replace = TRUE, prob=c(0.5, 0.5))
  propi<-sum(mostrai)
  NumOfHeads<-c(NumOfHeads,propi)
}

#sum(permut>=.605)
sum(NumOfHeads>=121)
hist(NumOfHeads)

heads<-data.frame(NumOfHeads)

pl1<-ggplot(heads, aes(x=NumOfHeads))+
  geom_histogram()+
  geom_vline(xintercept = 121, linetype=2,colour = "red")+
  labs(x="Year",y="% Male")

pl1

###
pbinom(121,200,0.5)
(1-pbinom(121,200,0.5))*100

tots<- seq(1:200)
binomial.df<-dbinom(tots,200,0.5)*200
cumbinomial.df<-pbinom(tots,200,0.5)*200

distr.ft<-data.frame(tots, binomial.df, cumbinomial.df)

pl2 <- ggplot(distr.ft, aes(x=tots, y=binomial.df/2))+
  geom_col()+
  coord_cartesian(xlim = c(70,130))+
  labs(x="Num. of Heads",y="% Perc")+
  geom_vline(xintercept = 121, linetype=2,colour = "red")

pl2


pl3 <- ggplot(distr.ft, aes(x=tots, y=cumbinomial.df/2))+
  geom_col()+
  coord_cartesian(xlim = c(75,125))+
  labs(x="Num. of Heads",y="% Perc")+
  geom_vline(xintercept = 121, linetype=2,colour = "red")

pl3

plot_grid(pl2, pl3, labels = c('A', 'B'), label_size = 12)

100-distr.ft$cumbinomial.df[distr.ft$tots==121]/2

## two-sided

pl4 <- ggplot(distr.ft, aes(x=tots, y=binomial.df/2))+
  geom_col()+
  coord_cartesian(xlim = c(70,130))+
  labs(x="Num. of Males",y="% Perc")+
  geom_vline(xintercept = c(79,121), linetype=2,colour = "red")

pl4

###

tots<- seq(1:200)
probx<-dhyper (tots,11000,11000,200)
distr.ft<-data.frame(tots, probx)

ggplot(distr.ft, aes(x=tots, y=probx))+
  geom_point()+
  geom_line()

sum(distr.ft$probx[distr.ft$tots>=121])*100




```

## Bootsrap 95% CI
```{r}
Mostra_Orig<-sample(Whale$length.m.,400, replace = FALSE) 

t.test(Mostra_Orig)

mostra_bootstrap<-c()

for (i in 1:5000){
  mostrai<-sample(Mostra_Orig,200, replace = TRUE)
  meani<-mean(mostrai)
  mostra_bootstrap<-c(mostra_bootstrap,meani)
}

## 95% Bootstrap CI
quantile(mostra_bootstrap,probs=c(0.025, 0.975))

## Plot
boot_mostra<-data.frame(mostra_bootstrap)

ggplot(boot_mostra, aes(x=mostra_bootstrap))+
  geom_histogram()+
  labs(x="resample mean")+
  geom_vline(xintercept = quantile(mostra_bootstrap,probs=c(0.025, 0.975)), linetype=2,colour = "red")
  


```

## t-test and Wilcoxon test 1 var
```{r}

sample1<-sample(Whale$length.m., 100, replace = FALSE)
summary(sample1)

mean(sample1)
sd(sample1)

t.test(sample1,alternative = "two.sided", mu = 13.5)
t.test(sample1,alternative = "two.sided", mu = 13.5, conf.level=0.99)
t.test(sample1,alternative = "two.sided", mu = 13.4)
t.test(sample1,alternative = "two.sided", mu = 13.6)
t.test(sample1,alternative = "two.sided", mu = 13.7)

## wilcoxon test
wilcox.test(sample1,alternative = "two.sided", mu = 13.5)
wilcox.test(sample1,alternative = "two.sided", mu = 13.4)
wilcox.test(sample1,alternative = "two.sided", mu = 13.6)

t.test(sample1,alternative = "two.sided", mu = 13.7)

ggplot(as.data.frame(sample1), aes(x=sample1))+
  geom_histogram(bins=25)+
  labs(x="Length(m)")+
  geom_vline(xintercept = 13.5, linetype=2,colour = "red")
```

## t-test and Wilcoxon test 2 var
```{r}

sample02<- sample(seq(1:23550), 200, replace = FALSE)

sample2<-Whale[sample02,]  

length(sample2$length.m.[sample2$sex=="Male"])
length(sample2$length.m.[sample2$sex=="Female"])

mean(sample2$length.m.[sample2$sex=="Male"])
mean(sample2$length.m.[sample2$sex=="Female"])

sd(sample2$length.m.[sample2$sex=="Male"])
sd(sample2$length.m.[sample2$sex=="Female"])

t.test(sample2$length.m.[sample2$sex=="Male"],sample2$length.m.[sample2$sex=="Female"],alternative = "two.sided")


wilcox.test(sample2$length.m.[sample2$sex=="Male"],sample2$length.m.[sample2$sex=="Female"],alternative = "two.sided")


ggplot(sample2, aes(x=length.m., group = sex))+
  geom_histogram(bins=20)+
  labs(x="Length(m)")+
  facet_wrap(~sex,nrow =2)

```

## F-test to compare 2 var
```{r}
var.test(sample2$length.m.[sample2$sex=="Male"],sample2$length.m.[sample2$sex=="Female"],alternative = "two.sided")


```


## Comparing proportions
```{r}
sample2$sex_cod<-ifelse(sample2$sex=="Male",1,0)

prop.test(sample2$sex_cod, n=1, p=0.5)
prop.test(113, n=200, p=0.5)

sample2$period<-ifelse(sample2$Year<1956, 0,1)

table(sample2$sex, sample2$period)

prop.test(c(59,45), n=c(104,96))

```

## ANOVA
```{r}
sample2$period2<-ifelse(sample2$Year<1930, "1925-1929",
                        ifelse(sample2$Year<1955, "1949-1954",
                        ifelse(sample2$Year<1960, "1955-1959","1960-1963")))

ggplot(sample2, aes(x=length.m., group = period2))+
  geom_histogram(bins=10)+
  labs(x="Length(m)")+
  facet_wrap(~period2,nrow =4)

model_ANOVA<-lm(length.m.~period2, data=sample2)
summary(model_ANOVA)

par(mfrow=c(2,2))
plot(model_ANOVA)

kruskal.test(length.m.~period2, data=sample2)
```

